services:
  playwright:
    build:
      context: ..
      dockerfile: CI/Dockerfile
    container_name: playwright-tests
    working_dir: /app
    volumes:
      - ../tests:/app/tests
      - ../config:/app/config
      - ../reports:/app/reports
