pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '20'))
        disableConcurrentBuilds()
        timestamps()
    }

    stages {

        stage('Prepare Workspace') {
            steps {
                script {
                    bat 'if not exist reports\\allure-results mkdir reports\\allure-results'
                    bat 'if not exist reports\\allure-history mkdir reports\\allure-history'
                }
            }
        }

        stage('Restore Allure History') {
            steps {
                script {
                    if (fileExists('reports/allure-history')) {
                        bat 'xcopy /E /I /Y reports\\allure-history\\* reports\\allure-results\\history\\'
                    }
                }
            }
        }

        stage('Start Docker Services') {
            steps {
                script {
                    bat 'docker compose -f ci/docker-compose.yml down || echo "No containers to stop"'
                    bat 'docker compose -f ci/docker-compose.yml up -d --build'
                }
            }
        }

        stage('Run Tests Inside Docker') {
            steps {
                script {
                    bat 'docker compose -f ci/docker-compose.yml exec playwright npx playwright test'
                }
            }
        }

        stage('Copy Allure Results From Container') {
            steps {
                script {
                    bat 'docker cp $(docker compose -f ci/docker-compose.yml ps -q playwright):/app/reports/allure-results reports/allure-results'
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                allure includeProperties: false, jdk: '', results: [[path: 'reports/allure-results']]
            }
        }

        stage('Save Allure History') {
            steps {
                script {
                    bat 'xcopy /E /I /Y allure-report\\history\\* reports\\allure-history\\'
                }
            }
        }
    }

    post {
        always {
            bat 'docker compose -f ci/docker-compose.yml down'
            archiveArtifacts artifacts: 'reports/allure-results/**', allowEmptyArchive: true
            archiveArtifacts artifacts: 'reports/allure-history/**', allowEmptyArchive: true
        }
    }
}
